BEGIN TRANSACTION;
DROP TABLE IF EXISTS "genre";
CREATE TABLE IF NOT EXISTS "genre" (
	"id"	INTEGER PRIMARY KEY,
	"nomgenre"	TEXT
);
INSERT INTO "genre" VALUES (0,'Animation');
INSERT INTO "genre" VALUES (1,'Comedy');
INSERT INTO "genre" VALUES (2,'Family');
INSERT INTO "genre" VALUES (3,'Adventure');
INSERT INTO "genre" VALUES (4,'Fantasy');
INSERT INTO "genre" VALUES (5,'Romance');
INSERT INTO "genre" VALUES (6,'Drama');
INSERT INTO "genre" VALUES (7,'Action');
INSERT INTO "genre" VALUES (8,'Crime');
INSERT INTO "genre" VALUES (9,'Thriller');
INSERT INTO "genre" VALUES (10,'Horror');
INSERT INTO "genre" VALUES (11,'History');
INSERT INTO "genre" VALUES (12,'Science');
INSERT INTO "genre" VALUES (13,'Fiction');
INSERT INTO "genre" VALUES (14,'Mystery');
INSERT INTO "genre" VALUES (15,'War');
INSERT INTO "genre" VALUES (16,'Foreign');
INSERT INTO "genre" VALUES (17,'Music');
INSERT INTO "genre" VALUES (18,'Documentary');
INSERT INTO "genre" VALUES (19,'Western');
INSERT INTO "genre" VALUES (20,'TV');
INSERT INTO "genre" VALUES (21,'Movie');
INSERT INTO "genre" VALUES (22,'Carousel');
INSERT INTO "genre" VALUES (23,'Productions');
INSERT INTO "genre" VALUES (24,'Vision');
INSERT INTO "genre" VALUES (25,'View');
INSERT INTO "genre" VALUES (26,'Entertainment');
INSERT INTO "genre" VALUES (27,'Telescene');
INSERT INTO "genre" VALUES (28,'Film');
INSERT INTO "genre" VALUES (29,'Group');
INSERT INTO "genre" VALUES (30,'Aniplex');
INSERT INTO "genre" VALUES (31,'GoHands');
INSERT INTO "genre" VALUES (32,'BROSTA');
INSERT INTO "genre" VALUES (33,'Mardock');
INSERT INTO "genre" VALUES (34,'Scramble');
INSERT INTO "genre" VALUES (35,'Production');
INSERT INTO "genre" VALUES (36,'Committee');
INSERT INTO "genre" VALUES (37,'Sentai');
INSERT INTO "genre" VALUES (38,'Filmworks');
INSERT INTO "genre" VALUES (39,'Odyssey');
INSERT INTO "genre" VALUES (40,'Media');
INSERT INTO "genre" VALUES (41,'Pulser');
COMMIT;
